### ISSUE TITLE
Uint16Array undefined for JS target?

### ISSUE THREAD

**Issue by Leadlace** [azrafe7/hxPako#2]
I'm trying to execute a simple compiled script with IE, but I get "Uint16Array undefined" error. Maybe haxe is targeting ES6 or something? Here is the source of my compiled script:

import haxe.io.UInt8Array;
import pako.Pako;

// ...

var inp = new UInt8Array(256);
for(i in 0...256) { inp.set(i, 48); }
var out = Pako.deflate(inp);
trace(out);

**Comment by azrafe7** [comment]
Hi,
typed arrays are not supported on older version of IE, so that may be the cause.

What IE version are you using?
What version of the haxe compiler?
What happens if you just try to use a UInt16Array (without importing pako)?

**Comment by azrafe7** [comment]
If "old IE version" is the problem you can try using a polyfill for typedarrays and see if it works for you (see https://github.com/photonstorm/phaser/issues/615 for a similar issue with a possible solution).

**Comment by Leadlace** [comment]
I tried using UInt16Array and UInt32Array, both fails on my test IE8, which I need to support. I looked at Haxe sources and UInt8Array has a compat mode, so it works fine in IE, but both UInt16Array and UInt32Array doesn't. Anyway this seems to be Haxe issue and not hxPako issue. Thanks for your help!
