### ISSUE TITLE
Haxe4 Preview 5 minor change

### ISSUE THREAD

**Issue by hoseyjoe** [azrafe7/hxPako#3]
Haxe4 Preview 5 required
pako.zlib.Inflate to have type defined in order to compile. Changed lines 228, 229 to
static var lenfix:Int32Array;
static var distfix:Int32Array;

I would do a pull request but...

**Comment by azrafe7** [comment]
Hey @hoseyjoe, thanks for heads-up. :smiley: 

Fixed in 09455eba10c1e3fbcd1965e7cc0922353d4b7ae1
